// Code generated by protoc-gen-go. DO NOT EDIT.
// source: school.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type School struct {
	SchoolId             string   `protobuf:"bytes,1,opt,name=schoolId,proto3" json:"schoolId,omitempty"`
	Schoolname           string   `protobuf:"bytes,2,opt,name=schoolname,proto3" json:"schoolname,omitempty"`
	EduMode              string   `protobuf:"bytes,3,opt,name=eduMode,proto3" json:"eduMode,omitempty"`
	Address              *Address `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Rating               float32  `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *School) Reset()         { *m = School{} }
func (m *School) String() string { return proto.CompactTextString(m) }
func (*School) ProtoMessage()    {}
func (*School) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{0}
}

func (m *School) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_School.Unmarshal(m, b)
}
func (m *School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_School.Marshal(b, m, deterministic)
}
func (m *School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_School.Merge(m, src)
}
func (m *School) XXX_Size() int {
	return xxx_messageInfo_School.Size(m)
}
func (m *School) XXX_DiscardUnknown() {
	xxx_messageInfo_School.DiscardUnknown(m)
}

var xxx_messageInfo_School proto.InternalMessageInfo

func (m *School) GetSchoolId() string {
	if m != nil {
		return m.SchoolId
	}
	return ""
}

func (m *School) GetSchoolname() string {
	if m != nil {
		return m.Schoolname
	}
	return ""
}

func (m *School) GetEduMode() string {
	if m != nil {
		return m.EduMode
	}
	return ""
}

func (m *School) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *School) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

type CreateSchoolReq struct {
	School               *School  `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchoolReq) Reset()         { *m = CreateSchoolReq{} }
func (m *CreateSchoolReq) String() string { return proto.CompactTextString(m) }
func (*CreateSchoolReq) ProtoMessage()    {}
func (*CreateSchoolReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{2}
}

func (m *CreateSchoolReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchoolReq.Unmarshal(m, b)
}
func (m *CreateSchoolReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchoolReq.Marshal(b, m, deterministic)
}
func (m *CreateSchoolReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchoolReq.Merge(m, src)
}
func (m *CreateSchoolReq) XXX_Size() int {
	return xxx_messageInfo_CreateSchoolReq.Size(m)
}
func (m *CreateSchoolReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchoolReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchoolReq proto.InternalMessageInfo

func (m *CreateSchoolReq) GetSchool() *School {
	if m != nil {
		return m.School
	}
	return nil
}

type CreateSchoolRes struct {
	School               *School  `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchoolRes) Reset()         { *m = CreateSchoolRes{} }
func (m *CreateSchoolRes) String() string { return proto.CompactTextString(m) }
func (*CreateSchoolRes) ProtoMessage()    {}
func (*CreateSchoolRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{3}
}

func (m *CreateSchoolRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchoolRes.Unmarshal(m, b)
}
func (m *CreateSchoolRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchoolRes.Marshal(b, m, deterministic)
}
func (m *CreateSchoolRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchoolRes.Merge(m, src)
}
func (m *CreateSchoolRes) XXX_Size() int {
	return xxx_messageInfo_CreateSchoolRes.Size(m)
}
func (m *CreateSchoolRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchoolRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchoolRes proto.InternalMessageInfo

func (m *CreateSchoolRes) GetSchool() *School {
	if m != nil {
		return m.School
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{4}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type ListSchoolRes struct {
	School               []*School `protobuf:"bytes,1,rep,name=school,proto3" json:"school,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListSchoolRes) Reset()         { *m = ListSchoolRes{} }
func (m *ListSchoolRes) String() string { return proto.CompactTextString(m) }
func (*ListSchoolRes) ProtoMessage()    {}
func (*ListSchoolRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{5}
}

func (m *ListSchoolRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSchoolRes.Unmarshal(m, b)
}
func (m *ListSchoolRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSchoolRes.Marshal(b, m, deterministic)
}
func (m *ListSchoolRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSchoolRes.Merge(m, src)
}
func (m *ListSchoolRes) XXX_Size() int {
	return xxx_messageInfo_ListSchoolRes.Size(m)
}
func (m *ListSchoolRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSchoolRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListSchoolRes proto.InternalMessageInfo

func (m *ListSchoolRes) GetSchool() []*School {
	if m != nil {
		return m.School
	}
	return nil
}

func init() {
	proto.RegisterType((*School)(nil), "model.School")
	proto.RegisterType((*Address)(nil), "model.Address")
	proto.RegisterType((*CreateSchoolReq)(nil), "model.CreateSchoolReq")
	proto.RegisterType((*CreateSchoolRes)(nil), "model.CreateSchoolRes")
	proto.RegisterType((*Void)(nil), "model.Void")
	proto.RegisterType((*ListSchoolRes)(nil), "model.ListSchoolRes")
}

func init() { proto.RegisterFile("school.proto", fileDescriptor_fdb068902851add0) }

var fileDescriptor_fdb068902851add0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0xa5, 0xbb, 0x6d, 0xfa, 0x7d, 0x53, 0xab, 0x30, 0x2c, 0x12, 0xf6, 0x20, 0xa5, 0x20, 0xf4,
	0x54, 0xa1, 0x82, 0x78, 0x54, 0x3c, 0x09, 0xee, 0xa5, 0x0b, 0xde, 0x63, 0x33, 0x68, 0x60, 0x77,
	0xa3, 0x49, 0x14, 0xfc, 0x37, 0xfe, 0x54, 0xd9, 0x24, 0x5d, 0x15, 0x15, 0xbc, 0xe5, 0xbd, 0x37,
	0x6f, 0xde, 0x1b, 0x02, 0x7b, 0x76, 0x78, 0xd0, 0x7a, 0xd5, 0x3e, 0x1a, 0xed, 0x34, 0x66, 0x6b,
	0x2d, 0x69, 0x55, 0xbf, 0x25, 0xc0, 0x96, 0x9e, 0xc7, 0x39, 0xfc, 0x0b, 0x13, 0xd7, 0x92, 0x27,
	0x55, 0xd2, 0xfc, 0xef, 0x77, 0x18, 0x8f, 0x00, 0xc2, 0x7b, 0x23, 0xd6, 0xc4, 0x27, 0x5e, 0xfd,
	0xc4, 0x20, 0x87, 0x9c, 0xe4, 0xf3, 0x42, 0x4b, 0xe2, 0x53, 0x2f, 0x8e, 0x10, 0x1b, 0xc8, 0x85,
	0x94, 0x86, 0xac, 0xe5, 0x69, 0x95, 0x34, 0x45, 0xb7, 0xdf, 0xfa, 0xe4, 0xf6, 0x32, 0xb0, 0xfd,
	0x28, 0xe3, 0x21, 0x30, 0x23, 0x9c, 0xda, 0xdc, 0xf3, 0xac, 0x4a, 0x9a, 0x49, 0x1f, 0x51, 0xbd,
	0x80, 0x3c, 0xce, 0x6e, 0x63, 0xc6, 0x65, 0xa1, 0xe1, 0xce, 0x3c, 0x83, 0xcc, 0x3a, 0xe1, 0xc6,
	0x6e, 0x01, 0x20, 0x42, 0x3a, 0x28, 0xf7, 0x1a, 0x3b, 0xf9, 0x77, 0x7d, 0x0e, 0x07, 0x57, 0x86,
	0x84, 0xa3, 0x70, 0x76, 0x4f, 0x4f, 0x78, 0x0c, 0x2c, 0xdc, 0xe2, 0xb7, 0x16, 0x5d, 0x19, 0x2b,
	0xc6, 0x89, 0x28, 0x7e, 0x77, 0xda, 0xbf, 0x3a, 0x19, 0xa4, 0xb7, 0x5a, 0xc9, 0xfa, 0x0c, 0xca,
	0x1b, 0x65, 0xdd, 0xcf, 0xfe, 0xe9, 0xaf, 0xfe, 0xee, 0x02, 0xca, 0xc0, 0x2c, 0xc9, 0xbc, 0xa8,
	0x81, 0xf0, 0x04, 0xe0, 0x63, 0x11, 0x16, 0xd1, 0xb5, 0xcd, 0x98, 0xcf, 0x22, 0xf8, 0x12, 0x74,
	0xc7, 0xfc, 0xaf, 0x9f, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x71, 0x74, 0x3c, 0xc0, 0x05, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchoolServiceClient is the client API for SchoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchoolServiceClient interface {
	ListSchool(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ListSchoolRes, error)
}

type schoolServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchoolServiceClient(cc *grpc.ClientConn) SchoolServiceClient {
	return &schoolServiceClient{cc}
}

func (c *schoolServiceClient) ListSchool(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ListSchoolRes, error) {
	out := new(ListSchoolRes)
	err := c.cc.Invoke(ctx, "/model.SchoolService/ListSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchoolServiceServer is the server API for SchoolService service.
type SchoolServiceServer interface {
	ListSchool(context.Context, *Void) (*ListSchoolRes, error)
}

// UnimplementedSchoolServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSchoolServiceServer struct {
}

func (*UnimplementedSchoolServiceServer) ListSchool(ctx context.Context, req *Void) (*ListSchoolRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchool not implemented")
}

func RegisterSchoolServiceServer(s *grpc.Server, srv SchoolServiceServer) {
	s.RegisterService(&_SchoolService_serviceDesc, srv)
}

func _SchoolService_ListSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ListSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.SchoolService/ListSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ListSchool(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchoolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.SchoolService",
	HandlerType: (*SchoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSchool",
			Handler:    _SchoolService_ListSchool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "school.proto",
}
